// Command genunicode generates tok/unicodedata.go from llama.cpp's checked-in
// Unicode tables.
//
// It generates rather than calling unicode.IsLetter because Go's Unicode tables
// ship with the toolchain, which would make token ids depend on the compiler
// (thousands of codepoints disagree on IsLetter).
//
// It takes llama.cpp's copy rather than the UCD because that file is a
// versioned artefact, verified to be exactly Unicode 15.1 across all
// codepoints, while llama.cpp's own generator downloads UCD/latest unpinned. It
// is not the specification (AGENTS.md RULE 7m); jitllm declares the version it
// carries.
package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) < 4 {
		fmt.Fprintln(os.Stderr, "usage: genunicode <unicode-data.cpp> <Scripts.txt> <out.go>")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	must(err)
	defer f.Close()

	pair := regexp.MustCompile(`\{0x([0-9A-Fa-f]+),\s*0x([0-9A-Fa-f]+)\}`)
	hex := regexp.MustCompile(`0x([0-9A-Fa-f]+)`)
	type rng struct {
		start uint32
		flags uint16
	}
	var ranges []rng
	var white []uint32
	lower := map[uint32]uint32{}
	upper := map[uint32]uint32{}
	triple := regexp.MustCompile(`\{0x([0-9A-Fa-f]+),\s*0x([0-9A-Fa-f]+),\s*0x([0-9A-Fa-f]+)\}`)
	var nfd [][3]uint32

	sec := ""
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		line := sc.Text()
		switch {
		case strings.Contains(line, "unicode_ranges_flags"):
			sec = "flags"
			continue
		case strings.Contains(line, "unicode_set_whitespace"):
			sec = "ws"
			continue
		case strings.Contains(line, "unicode_map_lowercase"):
			sec = "lower"
			continue
		case strings.Contains(line, "unicode_map_uppercase"):
			sec = "upper"
			continue
		case strings.Contains(line, "unicode_ranges_nfd"):
			sec = "nfd"
			continue
		}
		switch sec {
		case "flags":
			for _, m := range pair.FindAllStringSubmatch(line, -1) {
				s, _ := strconv.ParseUint(m[1], 16, 32)
				fl, _ := strconv.ParseUint(m[2], 16, 16)
				ranges = append(ranges, rng{uint32(s), uint16(fl)})
			}
		case "ws":
			for _, m := range hex.FindAllStringSubmatch(line, -1) {
				v, _ := strconv.ParseUint(m[1], 16, 32)
				white = append(white, uint32(v))
			}
		case "lower":
			for _, m := range pair.FindAllStringSubmatch(line, -1) {
				a, _ := strconv.ParseUint(m[1], 16, 32)
				b, _ := strconv.ParseUint(m[2], 16, 32)
				lower[uint32(a)] = uint32(b)
			}
		case "upper":
			for _, m := range pair.FindAllStringSubmatch(line, -1) {
				a, _ := strconv.ParseUint(m[1], 16, 32)
				b, _ := strconv.ParseUint(m[2], 16, 32)
				upper[uint32(a)] = uint32(b)
			}
		case "nfd":
			for _, m := range triple.FindAllStringSubmatch(line, -1) {
				a, _ := strconv.ParseUint(m[1], 16, 32)
				z, _ := strconv.ParseUint(m[2], 16, 32)
				d, _ := strconv.ParseUint(m[3], 16, 32)
				if a == 0 && z == 0 && d == 0 {
					continue // the table's sentinel, not a mapping
				}
				nfd = append(nfd, [3]uint32{uint32(a), uint32(z), uint32(d)})
			}
		}
	}
	must(sc.Err())
	sort.Slice(ranges, func(i, j int) bool { return ranges[i].start < ranges[j].start })
	sort.Slice(white, func(i, j int) bool { return white[i] < white[j] })
	keys := make([]uint32, 0, len(lower))
	for k := range lower {
		keys = append(keys, k)
	}
	ukeys := make([]uint32, 0, len(upper))
	for k := range upper {
		ukeys = append(ukeys, k)
	}
	sort.Slice(ukeys, func(i, j int) bool { return ukeys[i] < ukeys[j] })
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })

	// Han comes from the UCD, not llama.cpp: unicode-data.cpp carries no
	// scripts, and Scripts.txt under unicode.org/Public/15.1.0/ is pinned by
	// its URL, which is the same argument as above. llama.cpp's
	// unicode_cpt_is_han is a hand-written subset (CJK Ext A-F only, no
	// radicals, no U+3005, no compatibility ideographs) that would tokenize
	// Kimi differently from Moonshot's own tokenizer.
	han := hanRanges(os.Args[2])

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by scripts/genunicode. DO NOT EDIT.
//
// Source: llama.cpp src/unicode-data.cpp, verified to be exactly Unicode %s
// across all 1,114,112 codepoints (general category, simple lowercase, simple
// uppercase and White_Space).
//
// These tables exist so token ids do not depend on the Go toolchain. See
// scripts/genunicode for the argument; RULE 7m for why llama.cpp is the
// compatibility target and not the specification.

package tok

// UnicodeVersion is the version these tables encode. It is a DECLARED property
// of the engine, not whatever the compiler happened to ship.
const UnicodeVersion = %q

const (
	ucFlagUndefined = 1 << iota
	ucFlagNumber
	ucFlagLetter
	ucFlagSeparator
	ucFlagAccentMark
	ucFlagPunctuation
	ucFlagSymbol
	ucFlagControl
)

// ucRanges is (start, flags); a codepoint takes the flags of the last range
// whose start is <= it. %d entries.
var ucRanges = [...]struct {
	start uint32
	flags uint16
}{
`, "15.1.0", "15.1.0", len(ranges))
	for _, r := range ranges {
		fmt.Fprintf(&b, "\t{0x%06X, 0x%04X},\n", r.start, r.flags)
	}
	fmt.Fprintf(&b, "}\n\n// ucWhitespace is llama.cpp's White_Space set, %d codepoints.\nvar ucWhitespace = [...]uint32{\n", len(white))
	for _, w := range white {
		fmt.Fprintf(&b, "\t0x%06X,\n", w)
	}
	fmt.Fprintf(&b, "}\n\n// ucLower is the simple lowercase mapping, %d entries.\nvar ucLower = map[rune]rune{\n", len(keys))
	for _, k := range keys {
		fmt.Fprintf(&b, "\t0x%06X: 0x%06X,\n", k, lower[k])
	}
	b.WriteString("}\n")
	// The uppercase map is not for uppercasing: the flag table has one letter
	// bit, and o200k splits letter runs by case, so the two mappings separate
	// the classes (see ucUpperClass/ucLowerClass in unicodefn.go).
	fmt.Fprintf(&b, "\n// ucUpper is the simple uppercase mapping, %d entries. It exists to\n// separate Ll from Lm/Lo, not to uppercase anything -- see genunicode.\nvar ucUpper = map[rune]rune{\n", len(ukeys))
	for _, k := range ukeys {
		fmt.Fprintf(&b, "\t0x%06X: 0x%06X,\n", k, upper[k])
	}
	b.WriteString("}\n")
	var nHan int
	for _, r := range han {
		nHan += int(r[1]-r[0]) + 1
	}
	fmt.Fprintf(&b, "\n// ucHan is the Han SCRIPT, %d merged ranges over %d codepoints, from\n"+
		"// UCD %s Scripts.txt. It is a script rather than a category, which is why\n"+
		"// it is not in the flag table: kimi-k2 is the only pre-tokenizer that asks.\nvar ucHan = [...][2]uint32{\n", len(han), nHan, "15.1.0")
	for _, r := range han {
		fmt.Fprintf(&b, "\t{0x%06X, 0x%06X},\n", r[0], r[1])
	}
	b.WriteString("}\n")
	// The NFD table is a base-character map, not a decomposition: each range
	// maps a precomposed codepoint to the first codepoint of its canonical
	// decomposition, which is all BERT's strip_accents needs.
	sort.Slice(nfd, func(i, j int) bool { return nfd[i][0] < nfd[j][0] })
	fmt.Fprintf(&b, "\n// ucNFD maps a precomposed codepoint to the base of its canonical\n"+
		"// decomposition: (first, last, base), %d ranges. See genunicode.\nvar ucNFD = [...][3]uint32{\n", len(nfd))
	for _, r := range nfd {
		fmt.Fprintf(&b, "\t{0x%06X, 0x%06X, 0x%06X},\n", r[0], r[1], r[2])
	}
	b.WriteString("}\n")
	must(os.WriteFile(os.Args[3], []byte(b.String()), 0o644))
	fmt.Printf("wrote %s: %d ranges, %d whitespace, %d lowercase, %d uppercase, %d Han ranges (%d codepoints), %d NFD ranges\n",
		os.Args[3], len(ranges), len(white), len(keys), len(ukeys), len(han), nHan, len(nfd))
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}

// hanRanges reads the Han script's ranges out of a UCD Scripts.txt, merged and
// sorted. A line is "start[..end] ; Script # comment".
func hanRanges(path string) [][2]uint32 {
	f, err := os.Open(path)
	must(err)
	defer f.Close()
	var out [][2]uint32
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		line, _, _ := strings.Cut(sc.Text(), "#")
		cps, script, ok := strings.Cut(line, ";")
		if !ok || strings.TrimSpace(script) != "Han" {
			continue
		}
		cps = strings.TrimSpace(cps)
		lo, hi, ranged := strings.Cut(cps, "..")
		a, err := strconv.ParseUint(lo, 16, 32)
		must(err)
		b := a
		if ranged {
			b, err = strconv.ParseUint(hi, 16, 32)
			must(err)
		}
		out = append(out, [2]uint32{uint32(a), uint32(b)})
	}
	must(sc.Err())
	if len(out) == 0 {
		fmt.Fprintln(os.Stderr, "genunicode: no Han ranges in "+path)
		os.Exit(1)
	}
	sort.Slice(out, func(i, j int) bool { return out[i][0] < out[j][0] })
	// Merge touching ranges as well as overlapping ones: Scripts.txt lists
	// abutting ranges separately.
	merged := out[:1]
	for _, r := range out[1:] {
		last := &merged[len(merged)-1]
		if r[0] <= last[1]+1 {
			if r[1] > last[1] {
				last[1] = r[1]
			}
			continue
		}
		merged = append(merged, r)
	}
	return merged
}
