// Command gencover writes app/intercover.go: the runes the toolkit's embedded
// Inter has a glyph for, as ranges, and its mean advance. The app cannot ask Inter directly -- the
// toolkit embeds it in an internal package -- and FamilyFor needs to know when
// the default face can draw a rune before it reaches for a fallback.
//
//	go run ./app/internal/gencover > app/intercover.go
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/gogpu/gg/text"
)

func main() {
	out, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "github.com/gogpu/ui").Output()
	if err != nil {
		fail(err)
	}
	fonts := filepath.Join(strings.TrimSpace(string(out)), "internal", "render", "fonts")
	src := load(filepath.Join(fonts, "Inter-Regular.ttf"))
	bold := load(filepath.Join(fonts, "Inter-Bold.ttf"))
	p := src.Parsed()
	fmt.Println("// Code generated by app/internal/gencover from the toolkit's Inter-Regular.ttf and Inter-Bold.ttf. DO NOT EDIT.")
	fmt.Println()
	fmt.Println("package app")
	fmt.Println()
	fmt.Println("// interCover is every rune the embedded Inter draws, as inclusive ranges.")
	fmt.Println("var interCover = [][2]rune{")
	lo := rune(-1)
	for r := rune(0); r <= 0x2FFFF+1; r++ {
		// Controls map to .null, which draws nothing a person reads.
		has := r >= 0x20 && r <= 0x2FFFF && p.GlyphIndex(r) != 0
		switch {
		case has && lo < 0:
			lo = r
		case !has && lo >= 0:
			fmt.Printf("\t{0x%04X, 0x%04X},\n", lo, r-1)
			lo = -1
		}
	}
	fmt.Println("}")
	fmt.Println()
	fmt.Println("// interAdvance is Inter's mean advance per rune, in ems, over running")
	fmt.Println("// English: what Paragraph wraps prose by, since layout has no canvas to")
	fmt.Println("// measure with.")
	fmt.Printf("const interAdvance = %.4f\n", advance(src))
	fmt.Println()
	fmt.Println("// interBoldAdvance is the same for Inter Bold, which is wider: bold text")
	fmt.Println("// wrapped by the regular advance runs past its box.")
	fmt.Printf("const interBoldAdvance = %.4f\n", advance(bold))
}

// advance is a face's mean advance per rune over the probe, in ems.
func advance(src *text.FontSource) float64 {
	return src.Face(100).Advance(probe) / float64(len([]rune(probe))) / 100
}

func load(path string) *text.FontSource {
	data, err := os.ReadFile(path)
	if err != nil {
		fail(err)
	}
	src, err := text.NewFontSource(data)
	if err != nil {
		fail(err)
	}
	return src
}

// probe is running English with capitals, digits and punctuation in the
// proportions a reply has them.
const probe = "Paris is the capital of France. It sits on the Seine, and with about " +
	"2,100,000 people in the city proper it is the country's largest city; the " +
	"Louvre, the Eiffel Tower and Notre-Dame draw visitors all year round."

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
