// Command gentok generates tok/pretok/table.go: for every tokenizer.ggml.pre
// name a GGUF can carry, the ordered pipeline of typed stages that name denotes.
//
//	go run ./scripts/gentok tok/pretok/table.go
//	go run ./scripts/gentok -dump tok/testdata/pre tok/pretok/table.go
//
// -dump also writes every model's raw pre_tokenizer object, which is how the
// table's inputs become offline testdata instead of a network round trip.
//
// It emits data, not code: jitllm composes the stages at load time, so an
// unanticipated pipeline needs no new function and an unimplemented stage is a
// refusal rather than a routing to the nearest-looking splitter.
//
// The authority is the model, not llama.cpp (AGENTS.md RULE 7m). llama.cpp
// supplies only the directory of which HF repo defines each name; the pipeline
// is read from that model's own tokenizer.json. The resolved llama.cpp revision
// is recorded in the output so a regeneration is a reviewable diff.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/samyfodil/jitllm/tok/pretok"
)

func main() {
	dump := flag.String("dump", "", "also write each model's raw pre_tokenizer JSON object to this directory")
	flag.Parse()
	out := "tok/pretok/table.go"
	if flag.NArg() > 0 {
		out = flag.Arg(0)
	}
	if *dump != "" {
		if err := os.MkdirAll(*dump, 0o755); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
	dir, rev, err := fetchDirectory()
	if err != nil {
		fmt.Fprintln(os.Stderr, "directory:", err)
		os.Exit(1)
	}
	names := make([]string, 0, len(dir))
	for n := range dir {
		names = append(names, n)
	}
	sort.Strings(names)
	fmt.Fprintf(os.Stderr, "directory: %d BPE names from llama.cpp@%s\n", len(names), rev[:7])

	type row struct {
		name, repo, note string
		ops              []pretok.Op
	}
	var rows []row
	var unresolved, disagree []string
	for _, n := range names {
		if h, ok := handWritten[n]; ok {
			// Not a fetch failure: the model publishes no tokenizer.json at
			// all, which no retry or repo name fixes, so it is not listed as
			// unresolved.
			rows = append(rows, row{name: n, repo: h.repo, note: h.why, ops: h.ops})
			continue
		}
		// The first repo that resolves defines the name. Every other one that
		// resolves must give the same pipeline: an alias that tokenizes
		// differently is printed rather than silently shadowed.
		var ops []pretok.Op
		var raw []byte
		var repo string
		var errs []string
		for _, r := range dir[n] {
			o, rw, src, err := fetchPipeline(r)
			if err != nil {
				errs = append(errs, fmt.Sprintf("%s: %v", r, err))
				continue
			}
			if repo == "" {
				ops, raw, repo = o, rw, src
			} else if opsSource(o) != opsSource(ops) {
				disagree = append(disagree, fmt.Sprintf("%s: %s and %s give different pipelines", n, repo, r))
			}
		}
		if repo == "" {
			unresolved = append(unresolved, fmt.Sprintf("%s (%s)", n, strings.Join(errs, "; ")))
			continue
		}
		rows = append(rows, row{name: n, repo: repo, ops: ops})
		if *dump != "" {
			if err := dumpRaw(*dump, n, raw); err != nil {
				fmt.Fprintln(os.Stderr, "dump:", err)
				os.Exit(1)
			}
		}
	}
	fmt.Fprintf(os.Stderr, "resolved %d pipelines, %d unresolved\n", len(rows), len(unresolved))

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by scripts/gentok. DO NOT EDIT.
//
// Directory: llama.cpp@%s (which HF repo defines each tokenizer.ggml.pre name).
// Pipelines: each model's OWN tokenizer.json, fetched from HuggingFace.
//
// Regenerate with:  go run ./scripts/gentok tok/pretok/table.go
// Review the diff. A pipeline that gains or loses a stage is a tokenization
// change and should be read as one.

package pretok

// Table maps a pre-tokenizer name to the ordered stages it denotes.
// %d names resolved.
var Table = map[string][]Op{
`, rev, len(rows))
	for _, r := range rows {
		fmt.Fprintf(&b, "\t// %s\n\t%q: {", r.repo, r.name)
		for i, op := range r.ops {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(op.GoSource())
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	if len(unresolved) > 0 {
		b.WriteString("\n// Unresolved at generation time -- these names have NO entry above. One the\n" +
			"// legacy family splitters cover (tok/bpe.go) still tokenizes, unverified\n" +
			"// against its model; any other is refused rather than guessed (RULE 7):\n")
		for _, u := range unresolved {
			fmt.Fprintf(&b, "//   %s\n", u)
		}
	}
	if len(disagree) > 0 {
		b.WriteString("\n// Aliases that disagree with the defining model -- the entry above is the\n" +
			"// defining model's pipeline:\n")
		for _, d := range disagree {
			fmt.Fprintf(&b, "//   %s\n", d)
		}
	}
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", out)
}

// dumpRaw writes one model's pre_tokenizer to <dir>/<pre-name>.json, for
// offline testdata.
//
// The object is verbatim (a re-indent would make a diff against upstream
// unreadable) inside a one-line wrapper under a "pre_tokenizer" key, so
// pretok.ParsePreTokenizer can read the file back.
func dumpRaw(dir, name string, raw []byte) error {
	// The pre names come from llama.cpp's directory and are plain identifiers
	// (letters, digits, dots and dashes); a separator in one would mean the
	// upstream shape changed, and writing outside dir is not the way to find out.
	if name == "" || strings.ContainsAny(name, `/\`) || name == "." || name == ".." {
		return fmt.Errorf("refusing to dump %q: not a bare file name", name)
	}
	var b strings.Builder
	b.WriteString(`{"pre_tokenizer": `)
	b.Write(raw)
	b.WriteString("}\n")
	return os.WriteFile(filepath.Join(dir, name+".json"), []byte(b.String()), 0o644)
}

// handWritten is a pre-tokenizer this generator cannot derive, with the ops and
// the reason it cannot.
//
// It is not an escape hatch for a fetch that failed: everything else is parsed
// from the model's own tokenizer.json. An entry belongs here only when there is
// no tokenizer.json at all, and it names the artefact that replaces it.
var handWritten = map[string]struct {
	repo string
	why  string
	ops  []pretok.Op
}{
	// Moonshot publishes a `tiktoken.model` and a Python file, never a
	// tokenizer.json. The authority is the `pat_str` in tokenization_kimi.py,
	// byte-identical to Moonlight-16B-A3B's tokenization_moonshot.py:
	//
	//	[\p{Han}]+
	//	|[^\r\n\p{L}\p{N}]?[\p{Lu}\p{Lt}\p{Lm}\p{Lo}\p{M}&&[^\p{Han}]]*[\p{Ll}\p{Lm}\p{Lo}\p{M}&&[^\p{Han}]]+(?i:'s|'t|'re|'ve|'m|'ll|'d)?
	//	|[^\r\n\p{L}\p{N}]?[\p{Lu}\p{Lt}\p{Lm}\p{Lo}\p{M}&&[^\p{Han}]]+[\p{Ll}\p{Lm}\p{Lo}\p{M}&&[^\p{Han}]]*(?i:'s|'t|'re|'ve|'m|'ll|'d)?
	//	|\p{N}{1,3}| ?[^\s\p{L}\p{N}]+[\r\n]*|\s*[\r\n]+|\s+(?!\S)|\s+
	//
	// which is o200k -- gpt-4o's row below, flag for flag -- plus HanRuns, and
	// minus PunctSlash: the punctuation run ends [\r\n]* here where o200k's is
	// [\r\n/]*. tok/testdata/kimi_k2_split.json is the golden, generated from
	// that pattern.
	"kimi-k2": {
		repo: "moonshotai/Kimi-K2-Instruct (tokenization_kimi.py)",
		why:  "no tokenizer.json is published; the pat_str is the artefact",
		ops: []pretok.Op{
			{Kind: pretok.OpSplit, Split: pretok.SplitParams{
				Contractions: true, CaseFold: true, DigitGroup: 3,
				CaseRuns: true, SuffixContract: true, PunctSlash: false,
				HanRuns: true,
			}},
			{Kind: pretok.OpByteLevel},
		},
	},
}

// opsSource is a pipeline as the Go source it generates, which is how two
// fetched pipelines are compared.
func opsSource(ops []pretok.Op) string {
	var b strings.Builder
	for _, op := range ops {
		b.WriteString(op.GoSource())
		b.WriteString(";")
	}
	return b.String()
}
