package server

import (
	"bufio"
	"context"
	"io"
	"net/http"
	"regexp"
	"strconv"
	"strings"
	"testing"

	v1 "github.com/jitllm/jitllm/server/gen/jitllm/v1"
)

// sampleLine is one sample of the text exposition format: a name, optional
// labels of name="escaped value" pairs, and a float.
var sampleLine = regexp.MustCompile(`^([a-zA-Z_:][a-zA-Z0-9_:]*)(\{(?:[a-zA-Z_][a-zA-Z0-9_]*="(?:[^"\\]|\\.)*"(?:,[a-zA-Z_][a-zA-Z0-9_]*="(?:[^"\\]|\\.)*")*)?\})? (\S+)$`)

// scrape parses /metrics, failing on any line the format does not allow, a
// sample whose family has no TYPE, or a TYPE given twice. It returns each
// sample by its name and labels as written.
func scrape(t *testing.T, url string) map[string]float64 {
	t.Helper()
	r, err := http.Get(url + "/metrics")
	if err != nil {
		t.Fatal(err)
	}
	defer r.Body.Close()
	if ct := r.Header.Get("Content-Type"); !strings.HasPrefix(ct, "text/plain; version=0.0.4") {
		t.Fatalf("Content-Type %q", ct)
	}
	body, err := io.ReadAll(r.Body)
	if err != nil {
		t.Fatal(err)
	}
	typed := map[string]string{}
	out := map[string]float64{}
	sc := bufio.NewScanner(strings.NewReader(string(body)))
	for sc.Scan() {
		l := sc.Text()
		switch {
		case strings.HasPrefix(l, "# HELP "):
		case strings.HasPrefix(l, "# TYPE "):
			f := strings.Fields(l)
			if len(f) != 4 {
				t.Fatalf("bad TYPE line %q", l)
			}
			if _, dup := typed[f[2]]; dup {
				t.Fatalf("TYPE for %s twice", f[2])
			}
			switch f[3] {
			case "counter", "gauge", "summary", "histogram", "untyped":
			default:
				t.Fatalf("unknown type in %q", l)
			}
			typed[f[2]] = f[3]
		default:
			m := sampleLine.FindStringSubmatch(l)
			if m == nil {
				t.Fatalf("not a sample line: %q", l)
			}
			fam := m[1]
			if typed[fam] == "" {
				fam = strings.TrimSuffix(strings.TrimSuffix(fam, "_sum"), "_count")
				if typed[fam] != "summary" {
					t.Fatalf("sample %q has no TYPE", l)
				}
			}
			v, err := strconv.ParseFloat(m[3], 64)
			if err != nil {
				t.Fatalf("value in %q: %v", l, err)
			}
			out[m[1]+m[2]] = v
		}
	}
	return out
}

// TestMetricsParseAndMove: /metrics is well-formed exposition text and a
// generate moves its counters.
//
// VIOLATION SIGNATURE. Drop the lm.finished call from Generate and this
// fails with `jitllm_generates_total{model="small"} went 0 -> 0`.
func TestMetricsParseAndMove(t *testing.T) {
	e, _, c := loadedEngine(t, smallModel, "small", LoadOptions{})
	if _, err := e.CreateSession(SessionOptions{ModelID: "small", SessionID: "m", MaxSeq: 64}); err != nil {
		t.Fatal(err)
	}
	before := scrape(t, c.url)
	if before[`jitllm_models_loaded`] != 1 || before[`jitllm_sessions{model="small"}`] != 1 {
		t.Fatalf("models/sessions read %v", before)
	}
	if _, err := c.inference.Complete(context.Background(), req(&v1.GenerateRequest{SessionId: "m", Prompt: text(story), MaxTokens: 5})); err != nil {
		t.Fatal(err)
	}
	after := scrape(t, c.url)
	for _, k := range []string{
		`jitllm_generates_total{model="small"}`,
		`jitllm_tokens_generated_total{model="small"}`,
		`jitllm_tokens_prefilled_total{model="small"}`,
		`jitllm_prefill_seconds_count{model="small"}`,
		`jitllm_decode_seconds_count{model="small"}`,
		`jitllm_session_kv_bytes{model="small",session="m"}`,
	} {
		if after[k] <= before[k] {
			t.Errorf("%s went %g -> %g", k, before[k], after[k])
		}
	}
	// The decode time is counted, never negative: a 5-token generate of this
	// model fits inside one tick of a coarse clock (Windows), so its sum may
	// still read 0 there.
	if d := after[`jitllm_decode_seconds_sum{model="small"}`]; d < before[`jitllm_decode_seconds_sum{model="small"}`] {
		t.Errorf("decode_seconds_sum went backwards to %g", d)
	}
	if g := after[`jitllm_tokens_generated_total{model="small"}`] - before[`jitllm_tokens_generated_total{model="small"}`]; g != 5 {
		t.Errorf("a 5-token generate moved tokens_generated by %g", g)
	}
}
