#!/bin/sh
# Writes the Homebrew cask (jitllm.app) and formula (the CLI and the server)
# for one release, from that release's checksums.txt.
#
#   packaging/homebrew/generate.sh v1.2.3 dist/checksums.txt packaging/homebrew/tap
#
# The output directory is laid out as the tap repository jitllm/homebrew-tap
# is (Casks/jitllm.rb, Formula/jitllm.rb), so publishing is copying it there
# and pushing. Then:
#
#   brew install --cask jitllm/tap/jitllm   # jitllm.app, with jitllm and jitllmd on PATH
#   brew install jitllm/tap/jitllm          # jitllm and jitllmd only
#
# Every URL is the release's own asset and every sha256 is read from its
# checksums.txt; an asset missing from it is an error, not a blank.
set -eu

[ $# -eq 3 ] || { echo "usage: $0 <tag> <checksums.txt> <out-dir>" >&2; exit 2; }
tag=$1
sums=$2
out=$3
case $tag in v*) ;; *) echo "generate: tag $tag does not start with v" >&2; exit 2 ;; esac
version=${tag#v}
repo=${JITLLM_REPO:-jitllm/jitllm}
base="https://github.com/$repo/releases/download/$tag"

sha() {
	s=$(awk -v f="$1" '$2 == f { print $1 }' "$sums")
	[ -n "$s" ] || { echo "generate: $1 is not in $sums" >&2; exit 1; }
	echo "$s"
}

mkdir -p "$out/Casks" "$out/Formula"

dmg_arm=$(sha "jitllm_${version}_darwin_arm64.dmg")
dmg_intel=$(sha "jitllm_${version}_darwin_amd64.dmg")
cat >"$out/Casks/jitllm.rb" <<EOF
# Generated by packaging/homebrew/generate.sh from the $tag release; do not edit.
cask "jitllm" do
  arch arm: "arm64", intel: "amd64"

  version "$version"
  sha256 arm:   "$dmg_arm",
         intel: "$dmg_intel"

  url "https://github.com/$repo/releases/download/v#{version}/jitllm_#{version}_darwin_#{arch}.dmg"
  name "jitllm"
  desc "Inference engine for local language models, with a desktop app"
  homepage "https://jitllm.org"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :monterey"
  conflicts_with formula: "jitllm"

  app "jitllm.app"
  binary "#{appdir}/jitllm.app/Contents/Resources/bin/jitllm"
  binary "#{appdir}/jitllm.app/Contents/Resources/bin/jitllmd"

  uninstall launchctl: "org.jitllm.app.service",
            quit:      "org.jitllm.app"

  zap trash: [
    "~/Library/Application Support/jitllm",
    "~/Library/LaunchAgents/org.jitllm.app.service.plist",
    "~/Library/Logs/jitllm",
  ]
end
EOF

formula_os() { # os arch -> the url and sha256 lines
	for prog in jitllm jitllmd; do
		f="${prog}_${version}_$1_$2.tar.gz"
		s=$(sha "$f")
		if [ "$prog" = jitllm ]; then
			printf '      url "%s/%s"\n      sha256 "%s"\n' "$base" "$f" "$s"
		else
			printf '\n      resource "jitllmd" do\n        url "%s/%s"\n        sha256 "%s"\n      end\n' "$base" "$f" "$s"
		fi
	done
}

cat >"$out/Formula/jitllm.rb" <<EOF
# Generated by packaging/homebrew/generate.sh from the $tag release; do not edit.
class Jitllm < Formula
  desc "Inference engine for local language models: the jitllm CLI and the jitllmd server"
  homepage "https://jitllm.org"
  version "$version"
  license "Apache-2.0"

  on_macos do
    on_arm do
$(formula_os darwin arm64)
    end
    on_intel do
$(formula_os darwin amd64)
    end
  end

  on_linux do
    on_arm do
$(formula_os linux arm64)
    end
    on_intel do
$(formula_os linux amd64)
    end
  end

  def install
    bin.install "jitllm"
    resource("jitllmd").stage { bin.install "jitllmd" }
  end

  # brew services start jitllm: jitllmd on loopback, over Homebrew's models folder.
  service do
    run [opt_bin/"jitllmd", "serve", "-addr", "127.0.0.1:8080", "-models", var/"jitllm/models"]
    keep_alive successful_exit: false
    log_path var/"log/jitllmd.log"
    error_log_path var/"log/jitllmd.log"
  end

  def post_install
    (var/"jitllm/models").mkpath
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jitllm version")
  end
end
EOF

echo "$out/Casks/jitllm.rb"
echo "$out/Formula/jitllm.rb"
