package modelsdoc

// The human half of docs/models.md: which well-known models each name in the
// converter's lists covers. The names themselves come from the code; Render
// refuses a name with no line here and a line whose name the code no longer
// has, so a new architecture cannot land without saying what it runs, and a
// removed one cannot linger.

// ggufModels is one line per GGUF general.architecture name (convert.archOf).
var ggufModels = map[string]string{
	"apertus":        "Apertus 8B, 70B",
	"arcee":          "AFM-4.5B",
	"bailingmoe2":    "Ling 2.0 and Ring 2.0",
	"bert":           "all-MiniLM, mxbai-embed-large, bge-large, snowflake-arctic-embed (embeddings)",
	"clip":           "a vision tower (mmproj), converted into its text model's container",
	"cohere2":        "Command R7B, Command A",
	"command-r":      "Command-R, Aya, Aya Expanse",
	"dbrx":           "DBRX",
	"deepseek2":      "DeepSeek-V2, V2-Lite, Coder-V2, V3, R1; Kimi-K2; Moonlight; Kimi-VL's text model",
	"deepseek32":     "DeepSeek V3.2",
	"deepseek4":      "DeepSeek V4",
	"dots1":          "dots.llm1",
	"ernie4_5":       "ERNIE 4.5 dense models",
	"ernie4_5-moe":   "ERNIE 4.5 mixtures (21B-A3B, 300B-A47B)",
	"exaone4":        "EXAONE 4.0",
	"falcon":         "Falcon 7B, 40B, 180B",
	"falcon-h1":      "Falcon-H1",
	"gemma":          "Gemma 1",
	"gemma2":         "Gemma 2",
	"gemma3":         "Gemma 3; EmbeddingGemma (pooled)",
	"gemma3n":        "Gemma 3n E2B, E4B",
	"gemma4":         "Gemma 4",
	"glm4":           "GLM-4-0414; the text model of GLM-4.1V and GLM-4.6V-Flash",
	"glm4moe":        "GLM-4.5, GLM-4.6, GLM-4.5-Air; with M-RoPE sections the text model of GLM-4.5V and GLM-4.6V (the glm4vmoe graph)",
	"gpt-oss":        "gpt-oss 20B, 120B",
	"granite":        "Granite 3.x and 4.0 dense",
	"granitehybrid":  "Granite 4.0 hybrids (Mamba-2 beside attention)",
	"granitemoe":     "Granite 3.x mixtures",
	"hunyuan-dense":  "Hunyuan dense (0.5B to 7B)",
	"hunyuan-moe":    "Hunyuan-A13B",
	"hunyuan_vl":     "HunyuanOCR's text model (XD-RoPE)",
	"jamba":          "Jamba (Mamba-1 beside attention)",
	"kimi-k3":        "Kimi-K3",
	"lfm2":           "LFM2",
	"lfm2moe":        "LFM2-8B-A1B, LFM2-24B-A2B",
	"llama":          "Llama 2, 3, 3.1, 3.2, 3.3; Mistral 7B; Mixtral; SmolLM2; TinyLlama; the text model of SmolVLM, LLaVA and Janus-Pro",
	"llama4":         "Llama 4 Scout, Maverick",
	"mamba":          "Mamba, FalconMamba",
	"mamba2":         "Mamba-2, Mamba-Codestral",
	"minimax-m2":     "MiniMax-M2, M2.1, M2.5",
	"minimax-m3":     "MiniMax-M3",
	"mistral3":       "Ministral 3",
	"nemotron":       "Nemotron-4 Minitron, Nemotron-Mini",
	"nemotron_h":     "Nemotron-H, Nemotron Nano 2",
	"nemotron_h_moe": "Nemotron 3 Nano",
	"nomic-bert":     "nomic-embed-text (embeddings)",
	"olmo2":          "OLMo 2; OLMo 3 (its sliding window makes it the olmo3 graph)",
	"olmoe":          "OLMoE",
	"phi2":           "Phi-2",
	"phi3":           "Phi-3, Phi-3.5, Phi-4, Phi-4-mini",
	"phimoe":         "Phi-3.5-MoE, Phi-mini-MoE",
	"qwen2":          "Qwen2, Qwen2.5, QwQ, DeepSeek-R1-Distill-Qwen",
	"qwen2moe":       "Qwen1.5-MoE, Qwen2-57B-A14B",
	"qwen2vl":        "the text model of Qwen2-VL and Qwen2.5-VL",
	"qwen3":          "Qwen3 dense; Qwen3-Embedding (pooled)",
	"qwen35":         "Qwen3.5 dense",
	"qwen35moe":      "Qwen3.5 and Qwen3.6 mixtures",
	"qwen3moe":       "Qwen3 30B-A3B, 235B-A22B",
	"qwen3next":      "Qwen3-Next 80B-A3B",
	"qwen3vl":        "Qwen3-VL dense text models",
	"qwen3vlmoe":     "Qwen3-VL mixtures",
	"seed_oss":       "Seed-OSS 36B",
	"smollm3":        "SmolLM3",
	"stablelm":       "StableLM 2, StableLM 3B",
	"starcoder":      "StarCoder, StarCoderBase, SantaCoder",
	"starcoder2":     "StarCoder2",
}

// hfModels is one line per Hugging Face class (convert's hfArchTable).
var hfModels = map[string]string{
	"ApertusForCausalLM":             "Apertus",
	"ArceeForCausalLM":               "AFM-4.5B",
	"DeepseekV2ForCausalLM":          "DeepSeek-V2, V2-Lite, Coder-V2",
	"DeepseekV3ForCausalLM":          "DeepSeek-V3, R1, Kimi-K2, Moonlight",
	"Dots1ForCausalLM":               "dots.llm1",
	"Ernie4_5ForCausalLM":            "ERNIE 4.5 dense models",
	"Ernie4_5_MoeForCausalLM":        "ERNIE 4.5 mixtures",
	"Exaone4ForCausalLM":             "EXAONE 4.0",
	"GemmaForCausalLM":               "Gemma 1",
	"Glm4MoeForCausalLM":             "GLM-4.5, GLM-4.6, GLM-4.5-Air",
	"Glm4MoeLiteForCausalLM":         "GLM-4.7-Flash",
	"HunYuanDenseV1ForCausalLM":      "Hunyuan dense",
	"HunYuanMoEV1ForCausalLM":        "Hunyuan-A13B",
	"KimiK3ForConditionalGeneration": "Kimi-K3's text model, its experts compressed-tensors MXFP4",
	"KimiLinearForCausalLM":          "Kimi Linear (Kimi Delta Attention beside MLA; safetensors only)",
	"LlamaForCausalLM":               "Llama 2 and 3, Mistral 7B, SmolLM2, TinyLlama",
	"Ministral3ForCausalLM":          "Ministral 3's text model",
	"MixtralForCausalLM":             "Mixtral 8x7B, 8x22B",
	"Olmo2ForCausalLM":               "OLMo 2",
	"Olmo3ForCausalLM":               "OLMo 3 (its sliding window makes it the olmo3 graph)",
	"OlmoeForCausalLM":               "OLMoE",
	"Phi3ForCausalLM":                "Phi-3, Phi-3.5, Phi-4",
	"PhiMoEForCausalLM":              "Phi-3.5-MoE and its siblings, under their remote code's class name",
	"PhimoeForCausalLM":              "Phi-3.5-MoE and its siblings, under transformers' class name",
	"Qwen2ForCausalLM":               "Qwen2, Qwen2.5, QwQ",
	"Qwen2MoeForCausalLM":            "Qwen1.5-MoE, Qwen2-57B-A14B",
	"Qwen3ForCausalLM":               "Qwen3 dense",
	"Qwen3MoeForCausalLM":            "Qwen3 mixtures",
	"SeedOssForCausalLM":             "Seed-OSS",
	"SmolLM3ForCausalLM":             "SmolLM3",
}

// projectorModels is one line per vision projector (clip.projector_type,
// convert.Projectors).
var projectorModels = map[string]string{
	"gemma3":           "Gemma 3 (SigLIP)",
	"gemma3nv":         "Gemma 3n E2B, E4B (MobileNet-V5)",
	"gemma4v":          "Gemma 4",
	"glm4v":            "GLM-4.1V, GLM-4.5V, GLM-4.6V",
	"hunyuanvl":        "HunyuanOCR (HunyuanVL)",
	"idefics3":         "SmolVLM, Idefics3",
	"internvl":         "InternVL 2.5 and 3 (InternViT-300M; the 6B tower is refused)",
	"janus_pro":        "Janus-Pro",
	"kimivl":           "Kimi-VL (MoonViT)",
	"llama4":           "Llama 4 Scout, Maverick",
	"mlp":              "LLaVA and LLaVA-style models (a CLIP tower and a two-matrix MLP), llava-phi-3",
	"phi4":             "Phi-4-reasoning-vision-15B",
	"pixtral":          "Pixtral-12B, Mistral Small 3.x, Ministral 3",
	"qwen2.5vl_merger": "Qwen2.5-VL",
	"qwen2vl_merger":   "Qwen2-VL",
	"qwen3vl_merger":   "Qwen3-VL, Qwen3.5",
	"resampler":        "MiniCPM-V 2.6, o-2.6, 4.0, 4.5",
}
