// Package modelsdoc renders docs/models.md, the supported-models list, from
// the converter's own tables: convert.Architectures (the GGUF names),
// convert.HFClasses (the Hugging Face classes), convert.Projectors (the vision
// projectors), quant's type lists and the download catalogue. Every count in
// it is computed. scripts/genmodels writes it, and
// internal/srcgate.TestModelsDocIsGenerated fails when the file and the code
// part.
package modelsdoc

//go:generate go run ../../scripts/genmodels ../../docs/models.md

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/jitllm/jitllm/convert"
	"github.com/jitllm/jitllm/convert/library"
	"github.com/jitllm/jitllm/format/jlm"
	"github.com/jitllm/jitllm/format/quant"
)

// Path is where the rendered page lives, from the module root.
const Path = "docs/models.md"

// Command regenerates it.
const Command = "go run ./scripts/genmodels " + Path

// lines is the human half of the page (describe.go), passed in so a test can
// take one away.
type lines struct {
	gguf, hf, projector map[string]string
}

// Render is docs/models.md as the code makes it now. It fails when a name in
// the converter's lists has no line in describe.go, or a line names nothing.
func Render() ([]byte, error) {
	return render(lines{gguf: ggufModels, hf: hfModels, projector: projectorModels})
}

// covered checks that the keys of have are exactly names.
func covered(what string, names []string, have map[string]string) error {
	var missing, stale []string
	in := map[string]bool{}
	for _, n := range names {
		in[n] = true
		if strings.TrimSpace(have[n]) == "" {
			missing = append(missing, n)
		}
	}
	for n := range have {
		if !in[n] {
			stale = append(stale, n)
		}
	}
	sort.Strings(stale)
	if len(missing) > 0 {
		return fmt.Errorf("modelsdoc: %s %s in the code with no line in internal/modelsdoc/describe.go: "+
			"say which models it covers", what, strings.Join(missing, ", "))
	}
	if len(stale) > 0 {
		return fmt.Errorf("modelsdoc: internal/modelsdoc/describe.go describes %s %s, which the code does not have",
			what, strings.Join(stale, ", "))
	}
	return nil
}

func code(s string) string { return "`" + s + "`" }

func codes(ss []string) string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = code(s)
	}
	return strings.Join(out, ", ")
}

func render(d lines) ([]byte, error) {
	names := convert.Architectures()
	classes := convert.HFClasses()
	projectors := convert.Projectors()
	if err := covered("GGUF architecture", names, d.gguf); err != nil {
		return nil, err
	}
	if err := covered("Hugging Face class", classes, d.hf); err != nil {
		return nil, err
	}
	if err := covered("projector", projectors, d.projector); err != nil {
		return nil, err
	}

	// Group both lists by the graph each name converts to. The vision tower's
	// own name (clip) is not a text architecture; it goes with the projectors.
	type graph struct {
		arch    jlm.Arch
		gguf    []string
		classes []string
	}
	graphs := map[jlm.Arch]*graph{}
	at := func(a jlm.Arch) *graph {
		g := graphs[a]
		if g == nil {
			g = &graph{arch: a}
			graphs[a] = g
		}
		return g
	}
	var towers []string
	textNames := 0
	for _, n := range names {
		a, _ := convert.ArchitectureGraph(n)
		if a == jlm.ArchCLIP {
			towers = append(towers, n)
			continue
		}
		textNames++
		at(a).gguf = append(at(a).gguf, n)
	}
	for _, c := range classes {
		a, _ := convert.HFClassGraph(c)
		at(a).classes = append(at(a).classes, c)
	}
	order := make([]*graph, 0, len(graphs))
	ggufGraphs, hfGraphs, hfOnly := 0, 0, 0
	for _, g := range graphs {
		order = append(order, g)
		if len(g.gguf) > 0 {
			ggufGraphs++
		}
		if len(g.classes) > 0 {
			hfGraphs++
			if len(g.gguf) == 0 {
				hfOnly++
			}
		}
	}
	sort.Slice(order, func(i, j int) bool { return order[i].arch.String() < order[j].arch.String() })

	var encoders []string
	for _, n := range names {
		if a, _ := convert.ArchitectureGraph(n); a.Encoder() {
			encoders = append(encoders, n)
		}
	}

	var read []quant.Type
	for t := quant.Type(0); t < 256; t++ {
		if quant.Dequantable(t) {
			read = append(read, t)
		}
	}
	typeNames := func(ts []quant.Type) string {
		out := make([]string, len(ts))
		for i, t := range ts {
			out[i] = t.String()
		}
		return strings.Join(out, ", ")
	}

	vision := 0
	for _, m := range library.Models {
		if m.Vision() {
			vision++
		}
	}

	var b bytes.Buffer
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	p("# Supported models\n\n")
	p("<!-- Generated by `%s` from the converter's tables; do not edit by hand. -->\n\n", Command)
	p("This page is generated from the converter's own lists, so it is the list and not a description of it:\n")
	p("a GGUF architecture, Hugging Face class or vision projector that is not here is refused at conversion,\n")
	p("by name. `internal/srcgate.TestModelsDocIsGenerated` fails when the page and the code part; rerun\n")
	p("`%s`.\n\n", Command)
	p("- **%d** GGUF text architecture names (`general.architecture`, `convert.Architectures`) on **%d** graphs\n",
		textNames, ggufGraphs)
	p("- **%d** Hugging Face safetensors classes (`architectures` in `config.json`, `convert.HFClasses`) on **%d** graphs, **%d** of them reached only from safetensors\n",
		len(classes), hfGraphs, hfOnly)
	p("- **%d** graphs in all (`jlm.Arch`)\n", len(graphs))
	p("- **%d** vision projectors (`clip.projector_type`, `convert.Projectors`)\n", len(projectors))
	p("- **%d** embedding encoders, and pooling on any decoder\n", len(encoders))
	p("- **%d** weight types read (`quant.Dequantable`), **%d** of them packed quantizations (`quant.PackedTypes`)\n",
		len(read), len(quant.PackedTypes))
	p("- **%d** models in the download catalogue (`jitllm library`), **%d** of them with a vision tower\n\n",
		len(library.Models), vision)

	p("## Text architectures\n\n")
	p("One row per graph: several source names can convert to one graph. The file can refine a graph\n")
	p("further at conversion (a stated sliding window, M-RoPE sections); the Models column says where.\n\n")
	p("| Graph | GGUF `general.architecture` | Hugging Face class | Models |\n")
	p("|---|---|---|---|\n")
	for _, g := range order {
		var models []string
		describe := func(ns []string, m map[string]string) {
			for _, n := range ns {
				if len(ns) > 1 {
					models = append(models, code(n)+": "+m[n])
				} else {
					models = append(models, m[n])
				}
			}
		}
		if len(g.gguf) > 0 {
			describe(g.gguf, d.gguf)
		} else {
			describe(g.classes, d.hf)
		}
		gg, hc := codes(g.gguf), codes(g.classes)
		if gg == "" {
			gg = "--"
		}
		if hc == "" {
			hc = "--"
		}
		p("| %s | %s | %s | %s |\n", code(g.arch.String()), gg, hc, strings.Join(models, "; "))
	}

	p("\n## Hugging Face classes\n\n")
	p("`jitllm convert` reads a safetensors directory or repository whose `config.json` names one of these\n")
	p("classes; any other is refused, and `model_type` is not a fallback.\n\n")
	p("| Class | Graph | Models |\n|---|---|---|\n")
	for _, c := range classes {
		a, _ := convert.HFClassGraph(c)
		p("| %s | %s | %s |\n", code(c), code(a.String()), d.hf[c])
	}

	p("\n## Vision projectors\n\n")
	p("A vision model is one container: the text model's GGUF and its tower's (%s, the mmproj)\n", codes(towers))
	p("convert together, the text model one of the architectures above. The projector is the tower's\n")
	p("`clip.projector_type`.\n\n")
	p("| Projector | Models |\n|---|---|\n")
	for _, n := range projectors {
		p("| %s | %s |\n", code(n), d.projector[n])
	}

	p("\n## Embedding models\n\n")
	p("Encoders, run by the engine's encoder rather than its decoder graph:\n\n")
	for _, n := range encoders {
		p("- %s: %s\n", code(n), d.gguf[n])
	}
	p("\nAny decoder above also converts as an embedding model when its GGUF states `pooling_type` 1 (mean),\n")
	p("2 (first token) or 3 (last token): Qwen3-Embedding is `qwen3`, EmbeddingGemma `gemma3`. `pooling_type`\n")
	p("4, a reranker's head, is refused. Embeddings are served by `jitllm embed` and `/v1/embeddings`.\n")

	p("\n## Weight types\n\n")
	p("Read: %s.\n\n", typeNames(read))
	p("Packed quantizations: %s. A GGUF's quantization is kept; `-q8` stores a float safetensors model's\n", typeNames(quant.PackedTypes))
	p("matrices as Q8_0.\n")

	p("\n## Download catalogue\n\n")
	p("`jitllm convert NAME` fetches and converts these (`convert/library`). It is a curated subset of the\n")
	p("lists above, each entry downloaded, converted and made to generate before it was added.\n\n")
	p("| Name | Model | Architecture | Parameters | Weights | Images |\n|---|---|---|---|---|---|\n")
	for _, m := range library.Models {
		img := ""
		if m.Vision() {
			img = "yes"
		}
		p("| %s | %s | %s | %s | %s | %s |\n", code(m.Name), m.Title, code(m.Arch), m.Params, m.Quant, img)
	}
	return b.Bytes(), nil
}
