#!/bin/sh
# Writes the winget manifests for one release's Windows setup, from that
# release's checksums.txt.
#
#   packaging/winget/generate.sh v1.2.3 dist/checksums.txt packaging/winget/out
#
# The output is the directory a pull request to microsoft/winget-pkgs adds
# (manifests/j/jitllm/jitllm/<version>/), three files in the 1.10 schema: the
# version, the installer (both architectures, nullsoft, user scope) and the
# en-US locale. Submitting it is a separate, deliberate step
# (packaging/README.md); `winget validate --manifest <dir>` checks it first.
set -eu

[ $# -eq 3 ] || { echo "usage: $0 <tag> <checksums.txt> <out-dir>" >&2; exit 2; }
tag=$1
sums=$2
out=$3
case $tag in v*) ;; *) echo "generate: tag $tag does not start with v" >&2; exit 2 ;; esac
version=${tag#v}
repo=${JITLLM_REPO:-samyfodil/jitllm}
id=jitllm.jitllm
schema=1.10.0

sha() {
	s=$(awk -v f="$1" '$2 == f { print $1 }' "$sums")
	[ -n "$s" ] || { echo "generate: $1 is not in $sums" >&2; exit 1; }
	echo "$s" | tr a-f A-F
}

dir="$out/manifests/j/jitllm/jitllm/$version"
mkdir -p "$dir"

cat >"$dir/$id.yaml" <<EOF
# Generated by packaging/winget/generate.sh from the $tag release.
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.version.$schema.schema.json
PackageIdentifier: $id
PackageVersion: $version
DefaultLocale: en-US
ManifestType: version
ManifestVersion: $schema
EOF

{
	cat <<EOF
# Generated by packaging/winget/generate.sh from the $tag release.
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.installer.$schema.schema.json
PackageIdentifier: $id
PackageVersion: $version
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
Commands:
  - jitllm
  - jitllmd
ReleaseDate: $(date -u +%Y-%m-%d)
Installers:
EOF
	for a in amd64:x64 arm64:arm64; do
		f="jitllm-setup_${version}_windows_${a%%:*}.exe"
		cat <<EOF
  - Architecture: ${a#*:}
    InstallerUrl: https://github.com/$repo/releases/download/$tag/$f
    InstallerSha256: $(sha "$f")
EOF
	done
	cat <<EOF
ManifestType: installer
ManifestVersion: $schema
EOF
} >"$dir/$id.installer.yaml"

cat >"$dir/$id.locale.en-US.yaml" <<EOF
# Generated by packaging/winget/generate.sh from the $tag release.
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.defaultLocale.$schema.schema.json
PackageIdentifier: $id
PackageVersion: $version
PackageLocale: en-US
Publisher: jitllm
PublisherUrl: https://jitllm.org
PackageName: jitllm
PackageUrl: https://github.com/$repo
License: Apache-2.0
LicenseUrl: https://github.com/$repo/blob/$tag/LICENSE
ShortDescription: Inference engine for local language models, with a desktop app and a server.
Moniker: jitllm
Tags:
  - llm
  - inference
  - local-ai
ReleaseNotesUrl: https://github.com/$repo/releases/tag/$tag
ManifestType: defaultLocale
ManifestVersion: $schema
EOF

echo "$dir"
